### PR TITLE
fix: Swift 4.2 Compatible

### PR DESCRIPTION
**Pull request by jayahariv**
* fix the build error
* fix the warnings in code
* not fixed the storyboard warnings, as that will require changes in the layout.

### CODE REVIEW

**Comment by jayahariv** [comment]
@rajagp I cannot add you as reviewer, please check this.

**Comment by rajagp** [comment]
Thanks. Will do.

**Comment by rajagp** [comment]
Please update install_10.sh to point to CBL 2.1.3 .

**Comment by jayahariv** [comment]
done!

**Pull request merged**
